changed: ci

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -65,7 +65,16 @@ jobs:
           echo "$PRIVATE_KEY" > private_key.pem && chmod 600 private_key.pem
           ssh -o StrictHostKeyChecking=no -i private_key.pem ${USER_NAME}@${HOSTNAME} '
             docker pull docker.io/axoloot/portfolio:latest &&
-            docker stop portfolio || true &&
-            docker rm portfolio || true &&
-            docker run -d -v /home/ubuntu/certs/:/tmp/certs -p 80:80 -p 443:443 --name portfolio docker.io/axoloot/portfolio:latest
+            docker run -d --name portfolio_test -v /home/ubuntu/certs/:/tmp/certs -p 8080:80 -p 4443:443 docker.io/axoloot/portfolio:latest &&
+            sleep 30 && # Adjust as necessary for your container to start
+            if curl -f http://localhost:8080; then
+              docker stop portfolio || true &&
+              docker rm portfolio || true &&
+              docker rename portfolio_test portfolio
+            else
+              docker stop portfolio_test || true &&
+              docker rm portfolio_test || true &&
+              echo "New container failed health check. Keeping the old container running."
+              exit 1
+            fi
           '
